version: '3.8'
services:
  musihelp-service:
    build: .
    container_name: musihelp-container
    ports:
      - "8080:8080"
    volumes:
      # Esto hace que lo que se guarde en el contenedor aparezca en tu Mac
      - ./Musicxml:/app/Musicxml
    restart: unless-stopped